baseurl: /tpw

paginate: 10
paginate_path: "page:num"

excerpt_separator:  '<!--more-->'

title: "韦氏传媒"
description: "专注于高科技资讯传播与咨询，商业情报分析..."
url: "http://www.cnv4.com"
image: 
  path: "http://www.cnv4.com/images/open_graph_logo.png"
  width: 1200
  height: 630

leancloud :
  app_id   :  mKAIeIqN43aXYqu8DEvS2Hav-gzGzoHsz
  app_key  :  WL4XvXJ5fOSYBcPfW8rRsvBD
  enable: true
  
tag_page: /tags.html

 
